trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        command: buildAndPush
        repository: banking-service
        containerRegistry: acr-sc
        dockerfile: docker/Dockerfile
        tags: $(Build.BuildId)

- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - task: Kubernetes@1
      inputs:
        connectionType: Azure Resource Manager
        namespace: banking
        command: apply
        useConfigurationFile: true
        configuration: k8s/deployment.yaml
